@startuml
skinparam actorStyle awesome
rectangle Software{
:User: --> (Buy)
:User: --> (SaveData)
"Купити преміум" as (Buy)
"Записати дані" as (SaveData)

    usecase (Обробка Касою)
   (Обробка Касою) .> (Buy) : extends
}
@enduml